# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore server
      run: dotnet restore .\Prototype.ModularMVC\Prototype.ModularMVC.App\Prototype.ModularMVC.App.sln
    - name: Build server
      run: dotnet build --no-restore .\Prototype.ModularMVC\Prototype.ModularMVC.App\Prototype.ModularMVC.App.sln
    - name: Test server
      run: dotnet test --no-build --verbosity normal .\Prototype.ModularMVC\Prototype.ModularMVC.App\Prototype.ModularMVC.App.sln
    - name: Restore plugin
      run: dotnet restore .\Prototype.ModularMVC\Prototype.ModularMVC.ExamplePlugin\Prototype.ModularMVC.ExamplePlugin.sln
    - name: Build plugin
      run: dotnet build --no-restore .\Prototype.ModularMVC\Prototype.ModularMVC.ExamplePlugin\Prototype.ModularMVC.ExamplePlugin.sln
